### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jbguberman** [libbyh/methods-f16#11]
Got the following build error when I uploaded my most recent post:

> The page build failed with the following error:
> 
> The value 'nil' was passed to a date-related filter that expects valid dates in `sitemap.xml` or one of its layouts. For more information, see https://help.github.com/articles/page-build-failed-date-is-not-a-valid-datetime/.
> 
> For information on troubleshooting Jekyll see:
> 
>  https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by libbyh** [comment]
Fixed by 37768c929a346b921cdc560c2f308e9bf29eb7f8
