### ISSUE TITLE
Excerpts are too long

### ISSUE THREAD

**Issue by libbyh** [libbyh/methods-f16#3]
Need excerpts on posts list to be a little shorter so we can see more of them.

**Comment by libbyh** [comment]
@sebbnet fixed in PR #8

**Comment by uyx6345** [comment]
Prof Hemphill

This is Chang Cheng. I'm sorry that I missed the class today because I got
into an traffic accident and am now in hospital. Did I missed anything or
if there is anything I have to make up with? Please let me know if possible.

> ## 

Best regard.

Chang Cheng
